name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore SkaAI.sln
      - name: Build
        run: dotnet build SkaAI.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test SkaAI.sln --no-build --configuration Release || true
      - name: Publish Artifacts
        run: dotnet publish SkaAI.sln --no-build --configuration Release --output ./artifacts 